version: 2

project_name: skillbox

builds:
  - id: skillbox-server
    main: ./cmd/skillbox-server
    binary: skillbox-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X github.com/devs-group/skillbox/internal/version.Version={{.Version}}
      - -X github.com/devs-group/skillbox/internal/version.Commit={{.Commit}}
      - -X github.com/devs-group/skillbox/internal/version.BuildTime={{.Date}}

  - id: skillbox-cli
    main: ./cmd/skillbox
    binary: skillbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X github.com/devs-group/skillbox/internal/version.Version={{.Version}}
      - -X github.com/devs-group/skillbox/internal/version.Commit={{.Commit}}
      - -X github.com/devs-group/skillbox/internal/version.BuildTime={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
